// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/template-tasks/{id}": {
            "get": {
                "description": "Find template task attachment by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Template Task Attachments"
                ],
                "summary": "Find template task attachment by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template Task Attachment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.TemplateTaskAttachmentResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete template task attachment by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Template Task Attachments"
                ],
                "summary": "Delete template task attachment by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template Task Attachment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "success delete template task attachment",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/covers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Find all covers with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Covers"
                ],
                "summary": "Find all covers with pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Created At",
                        "name": "created_at",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.CoverResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new cover",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Covers"
                ],
                "summary": "Create a new cover",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.CoverResponse"
                        }
                    }
                }
            }
        },
        "/covers/update": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update cover by id",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Covers"
                ],
                "summary": "Update cover by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "File",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.CoverResponse"
                        }
                    }
                }
            }
        },
        "/covers/upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upload cover",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Covers"
                ],
                "summary": "Upload cover",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.CoverResponse"
                        }
                    }
                }
            }
        },
        "/covers/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Find cover by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Covers"
                ],
                "summary": "Find cover by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.CoverResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete cover by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Covers"
                ],
                "summary": "Delete cover by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/employee-tasks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Find all employee task paginated",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee Task"
                ],
                "summary": "Find all employee task paginated",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Created At",
                        "name": "created_at",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.EmployeeTaskResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create new employee task",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee Task"
                ],
                "summary": "Create new employee task",
                "parameters": [
                    {
                        "description": "Create Template Task",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateEmployeeTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.EmployeeTaskResponse"
                        }
                    }
                }
            }
        },
        "/employee-tasks/count": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Count employee task by kanban and employee id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee Task"
                ],
                "summary": "Count employee task by kanban and employee id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kanban",
                        "name": "kanban",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Employee ID",
                        "name": "employee_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.EmployeeTaskResponse"
                        }
                    }
                }
            }
        },
        "/employee-tasks/employee": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Find all employee task by employee id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee Task"
                ],
                "summary": "Find all employee task by employee id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee ID",
                        "name": "employee_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.EmployeeTaskResponse"
                        }
                    }
                }
            }
        },
        "/employee-tasks/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Find employee task by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee Task"
                ],
                "summary": "Find employee task by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.EmployeeTaskResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update employee task",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee Task"
                ],
                "summary": "Update employee task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Employee Task",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateEmployeeTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.EmployeeTaskResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete employee task",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Employee Task"
                ],
                "summary": "Delete employee task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Employee Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success delete employee task",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/template-tasks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Find all template tasks with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Template Tasks"
                ],
                "summary": "Find all template tasks with pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page Size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Created At",
                        "name": "created_at",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.TemplateTaskResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create new template task",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Template Tasks"
                ],
                "summary": "Create new template task",
                "parameters": [
                    {
                        "description": "Create Template Task",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateTemplateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.TemplateTaskResponse"
                        }
                    }
                }
            }
        },
        "/template-tasks/update": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update template task by id",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Template Tasks"
                ],
                "summary": "Update template task by id",
                "parameters": [
                    {
                        "description": "Update Template Task",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateTemplateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.TemplateTaskResponse"
                        }
                    }
                }
            }
        },
        "/template-tasks/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Find template task by id",
                "tags": [
                    "Template Tasks"
                ],
                "summary": "Find template task by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.TemplateTaskResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete template task by id",
                "tags": [
                    "Template Tasks"
                ],
                "summary": "Delete template task by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/universities": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Find all universities",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Universities"
                ],
                "summary": "Find all universities",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.UniversityResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.EmployeeTaskKanbanEnum": {
            "type": "string",
            "enum": [
                "TO_DO",
                "IN_PROGRESS",
                "NEED_REVIEW",
                "COMPLETED"
            ],
            "x-enum-varnames": [
                "EMPLOYEE_TASK_KANBAN_ENUM_TODO",
                "EPMLOYEE_TASK_KANBAN_ENUM_IN_PROGRESS",
                "EMPLOYEE_TASK_KANBAN_ENUM_NEED_REVIEW",
                "EMPLOYEE_TASK_KANBAN_ENUM_COMPLETED"
            ]
        },
        "entity.EmployeeTaskPriorityEnum": {
            "type": "string",
            "enum": [
                "LOW",
                "MEDIUM",
                "HIGH"
            ],
            "x-enum-varnames": [
                "EMPLOYEE_TASK_PRIORITY_ENUM_LOW",
                "EMPLOYEE_TASK_PRIORITY_ENUM_MEDIUM",
                "EMPLOYEE_TASK_PRIORITY_ENUM_HIGH"
            ]
        },
        "entity.EmployeeTaskStatusEnum": {
            "type": "string",
            "enum": [
                "ACTIVE",
                "INACTIVE"
            ],
            "x-enum-varnames": [
                "EMPLOYEE_TASK_STATUS_ENUM_ACTIVE",
                "EMPLOYEE_TASK_STATUS_ENUM_INACTIVE"
            ]
        },
        "entity.TemplateTaskPriorityEnum": {
            "type": "string",
            "enum": [
                "LOW",
                "MEDIUM",
                "HIGH"
            ],
            "x-enum-varnames": [
                "TEMPLATE_TASK_PRIORITY_ENUM_LOW",
                "TEMPLATE_TASK_PRIORITY_ENUM_MEDIUM",
                "TEMPLATE_TASK_PRIORITY_ENUM_HIGH"
            ]
        },
        "entity.TemplateTaskStatusEnum": {
            "type": "string",
            "enum": [
                "ACTIVE",
                "INACTIVE"
            ],
            "x-enum-varnames": [
                "TEMPLATE_TASK_STATUS_ENUM_ACTIVE",
                "TEMPLATE_TASK_STATUS_ENUM_INACTIVE"
            ]
        },
        "multipart.FileHeader": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string"
                },
                "header": {
                    "$ref": "#/definitions/textproto.MIMEHeader"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "request.CreateEmployeeTaskRequest": {
            "type": "object",
            "required": [
                "cover_path",
                "employee_id",
                "end_date",
                "name",
                "priority",
                "start_date"
            ],
            "properties": {
                "cover_path": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "employee_id": {
                    "type": "string"
                },
                "employee_task_attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.EmployeeTaskAttachmentRequest"
                    }
                },
                "employee_task_checklists": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.EmployeeTaskChecklistRequest"
                    }
                },
                "end_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "template_task_id": {
                    "type": "string"
                }
            }
        },
        "request.CreateTemplateTaskRequest": {
            "type": "object",
            "required": [
                "cover_path",
                "name",
                "priority",
                "status"
            ],
            "properties": {
                "cover_path": {
                    "description": "CoverFile               *multipart.FileHeader           ` + "`" + `form:\"cover_file\" validate:\"required\"` + "`" + `",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "due_duration": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "template_task_attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.TemplateTaskAttachmentRequest"
                    }
                },
                "template_task_checklists": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.TemplateTaskChecklistRequest"
                    }
                }
            }
        },
        "request.EmployeeTaskAttachmentRequest": {
            "type": "object",
            "required": [
                "file"
            ],
            "properties": {
                "file": {
                    "$ref": "#/definitions/multipart.FileHeader"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "request.EmployeeTaskChecklistRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "is_checked": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "verified_by": {
                    "type": "string"
                }
            }
        },
        "request.TemplateTaskAttachmentRequest": {
            "type": "object",
            "required": [
                "file"
            ],
            "properties": {
                "file": {
                    "$ref": "#/definitions/multipart.FileHeader"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "request.TemplateTaskChecklistRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "request.UpdateEmployeeTaskRequest": {
            "type": "object",
            "required": [
                "cover_path",
                "employee_id",
                "end_date",
                "id",
                "name",
                "priority",
                "start_date"
            ],
            "properties": {
                "cover_path": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "employee_id": {
                    "type": "string"
                },
                "employee_task_attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.EmployeeTaskAttachmentRequest"
                    }
                },
                "employee_task_checklists": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.EmployeeTaskChecklistRequest"
                    }
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_done": {
                    "type": "string",
                    "enum": [
                        "YES",
                        "NO"
                    ]
                },
                "kanban": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "priority": {
                    "type": "string"
                },
                "proof": {
                    "$ref": "#/definitions/multipart.FileHeader"
                },
                "proof_path": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "template_task_id": {
                    "type": "string"
                },
                "verified_by": {
                    "type": "string"
                }
            }
        },
        "request.UpdateTemplateTaskRequest": {
            "type": "object",
            "required": [
                "cover_path",
                "id",
                "name",
                "priority",
                "status"
            ],
            "properties": {
                "cover_path": {
                    "description": "CoverFile               *multipart.FileHeader           ` + "`" + `form:\"cover_file\" validate:\"required\"` + "`" + `",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "due_duration": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "template_task_attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.TemplateTaskAttachmentRequest"
                    }
                },
                "template_task_checklists": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.TemplateTaskChecklistRequest"
                    }
                }
            }
        },
        "response.CoverResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "path_origin": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "response.EmployeeTaskAttachmentResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "employee_task_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "path_origin": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "response.EmployeeTaskChecklistResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "employee_task_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_checked": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "verified_by": {
                    "type": "string"
                },
                "verified_by_name": {
                    "type": "string"
                }
            }
        },
        "response.EmployeeTaskResponse": {
            "type": "object",
            "properties": {
                "cover_path": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "employee_id": {
                    "type": "string"
                },
                "employee_name": {
                    "type": "string"
                },
                "employee_task_attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.EmployeeTaskAttachmentResponse"
                    }
                },
                "employee_task_checklists": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.EmployeeTaskChecklistResponse"
                    }
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_done": {
                    "type": "string"
                },
                "kanban": {
                    "$ref": "#/definitions/entity.EmployeeTaskKanbanEnum"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "priority": {
                    "$ref": "#/definitions/entity.EmployeeTaskPriorityEnum"
                },
                "proof": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/entity.EmployeeTaskStatusEnum"
                },
                "template_task": {
                    "$ref": "#/definitions/response.TemplateTaskResponse"
                },
                "template_task_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "verified_by": {
                    "type": "string"
                },
                "verified_by_name": {
                    "type": "string"
                }
            }
        },
        "response.TemplateTaskAttachmentResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "path_origin": {
                    "type": "string"
                },
                "template_task_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "response.TemplateTaskChecklistResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "template_task_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "response.TemplateTaskResponse": {
            "type": "object",
            "properties": {
                "coverPath": {
                    "type": "string"
                },
                "cover_path_origin": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "due_duration": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "$ref": "#/definitions/entity.TemplateTaskPriorityEnum"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/entity.TemplateTaskStatusEnum"
                },
                "template_task_attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.TemplateTaskAttachmentResponse"
                    }
                },
                "template_task_checklists": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.TemplateTaskChecklistResponse"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "response.UniversityResponse": {
            "type": "object",
            "properties": {
                "alpha_two_code": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "textproto.MIMEHeader": {
            "type": "object",
            "additionalProperties": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Bearer token for authentication",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8001",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Julong Onboarding API Docs",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
